[pytest]
addopts = -s -n auto
testpaths= tests
log_cli = true
log_cli_level = INFO
log_format = %(asctime)s [%(levelname)s] %(message)s
markers=
    iframe: iframe test cases
    only: run specific tests